name: Deploy www.nvo.one

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Deploy-to-S3:
    runs-on: ubuntu-latest

    steps:
      # Configure AWS Credentials
      - name: Configure AWS Credentials
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
          echo "region=${AWS_DEFAULT_REGION}" >> ~/.aws/credentials
      
      # Copy from github to runner
      - name: Checkout file to runner
        uses: actions/checkout@v4
        with: 
          submodules: recursive
            
      # Install Hugo
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ' 0.122.0'

      # Make Public
      - name: Generate Public folder
        run: hugo --destination public
        
      # copy Public to website bucket
      - name: copy to s3
        run: aws s3 cp ~/work/MyPaperModSite/MyPaperModSite/public s3://www.nvo.one --recursive

      # invalidate cloudfront distribution
      - name: invalidate
        run: aws cloudfront create-invalidation --distribution-id E2CCQI91M1HV67 --paths "/*"