name: Deploy www.nvo.one

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Deploy-to-S3:
    runs-on: ubuntu-latest

    steps:
      # Login AWS CLI
      - name: Verify aws
        run: aws --version

      - name: Configure AWS Credentials
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
          echo "region=${AWS_DEFAULT_REGION}" >> ~/.aws/credentials
      
      - name: verify aws credential
        run: aws configure list
      
      - name: verify s3 permission
        run: aws s3 ls

      # Copy from github to runner
      - name: Checkout file to runner
        uses: actions/checkout@v2

      # Verify path
      - name: Get current path
        run: pwd command

      # Install Hugo
      - name: Install Hugo
        run: sudo apt install hugo

      # Verify Hugo version
      - name: Verify hugo
        run: hugo
      
      # get folders
      - name: verify path
        run: ls

      # get current path
      - name: get current path
        run: pwd command

      # copy Public to website bucket
      - name: copy to s3
        run: aws s3 cp ~/work/MyPaperModSite/MyPaperModSite/public s3://www.nvo.one --recursive   